version: '2'
services:
  db:
    image: mysql:5.7.12
    volumes:
      - "./.data/db:/var/lib/mysql"
        #- "./.data/install_wordpress.sql:/docker-entrypoint-initdb.d/install_wordpress.sql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"

  wordpress:
    depends_on:
      - db
    build:
      context: ./wordpress
    volumes:
      - "./.html:/var/www/html"
    ports:
      - "${WORDPRESS_PORT}:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "1025:1025"
      - "8025:8025"
