version: '2'
services:
  db:
    image: mysql:5.7.12
    volumes:
      - "./.data/db:/var/lib/mysql"
      - "./.data/install_wordpress.sql:/docker-entrypoint-initdb.d/install_wordpress.sql"
      - "./.data/patch.sql:/docker-entrypoint-initdb.d/patch.sql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"

  wordpress:
    depends_on:
      - db
    build:
      context: ./wordpress
    volumes:
      - "./.html:/var/www/html"
      - "./${WORDPRESS_GIT_REPO}/wp-content:/var/www/html/wp-content"
    ports:
      - "${WORDPRESS_PORT}:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "1025:1025"
      - "8025:8025"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - db
    volumes:
      - /sessions
